name: inside_the_circuit
description: "Inside the Circuit - a mobile top-down survival game built with Flutter and Flame."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flame: 1.22.0
  flame_audio: 2.10.6
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences_platform_interface: ^2.4.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
